### ISSUE TITLE
Improve Schema

### ISSUE THREAD

**Issue by kmccallsdsu** [bihnkim/DapGenius#7]
Come talk to me about deciding whether or not to store artists/albums.

Choosing not to means you will want to store artist_name and album_name in the songs table.

How will annotations know where they are annotating?

Will you be able to comment on anything but annotations? Comments on comments?

**Comment by bihnkim** [comment]
At this time, I have decided store the artist and album names as columns in the songs table. I've added start/end indexes to annotations, and I have added a reference to the polymorphic "commentable" in the comments table to provide the option to comment on anything. I am still considering on whether a user can comment on a comment, with weighing on styling and if it makes sense to do so.
